vm:
  box: nfq/wheezy
  box_url: nfq/wheezy
  hostname: reservations.dev # generated
  hostnames: []
  cpu: 1
  memory: 1024
  network:
    private_network: 192.168.56.12
    guest_port: 22
    host_port: 9660
  sync:
    source: ./
    target: /var/www/reservations.dev/
