services:
    reservations.frontend.registration.form.type:
        class: Reservations\FrontendBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: reservations_user_registration }

#    reservations.frontend.form.type.profile:
#        class: Reservations\FrontendBundle\Form\Type\ProfileFormType
#        tags:
#            - { name: form.type, alias: reservations_user_profile }
