services:
    acme_user.registration.form.type:
        class: Reservations\FrontendBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: reservations_user_registration }
