services:
    reservations_user.registration.form.type:
        class: Reservations\FrontendBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: reservations_user_registration }

    reservations_user.profile.form.type:
        class: Reservations\FrontendBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: reservations_user_profile }
