reservations_core_homepage:
    path:     /
    defaults: { _controller: ReservationsFrontendBundle:Default:index }

reservations_core_login:
    path:     /verslui
    defaults: { _controller: ReservationsFrontendBundle:Default:login }
