reservations_core_homepage:
    path:     /
    defaults: { _controller: ReservationsFrontendBundle:Search:index }

reservations_core_showpage:
    path:     /show/{id}
    defaults: { _controller: ReservationsFrontendBundle:Search:show }

reservations_core_ajax_reservation:
    path:     /ajax-reservation/{id}
    defaults: { _controller: ReservationsFrontendBundle:Reservations:ajaxReservation }

reservations_core_dashboard:
    path:     /dashboard
    defaults: { _controller: ReservationsFrontendBundle:Reservations:index }

reservations_core_dashboard_reservations_page:
    path:     /reservations/{page}
    defaults: { _controller: ReservationsFrontendBundle:Reservations:reservations }

reservations_core_dashboard_reservations_status:
    path:     /reservations/{id}/{status}
    defaults: { _controller: ReservationsFrontendBundle:Reservations:changeStatus }

reservations_frontend_bar:
    resource: "@ReservationsCoreBundle/Resources/config/routing/bar.yml"
    prefix:   /bars
