reservations_core_homepage:
    path:     /
    defaults: { _controller: ReservationsFrontendBundle:Default:index }

reservations_core_showpage:
    path:     /show/{id}
    defaults: { _controller: ReservationsFrontendBundle:Default:show }

#reservations_core_control_panel:
#    path:     /control-panel
